name: Build LaTeX PDF

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'main.pdf'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX
        run: |
          pdflatex -interaction=nonstopmode main.tex
          pdflatex -interaction=nonstopmode main.tex

      - name: Commit PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add main.pdf
          git commit -m "Auto-build main.pdf" || echo "No changes to commit"
          git push
